version: "3.8"

services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      TRUSTED_ORIGINS: "http://localhost:8081 http://127.0.0.1:8081"

  flask_app:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0 --port=8001
    volumes:
      - ./flask_app:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_APP=horse_pedigree_api.py

  react_app:
    build:
      context: ./react_app
    volumes:
      - ./react_app:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - flask_app
    command: yarn start

volumes:
  db_data:
